name: aprendiendo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  convex_bottom_bar:
  image_picker: 
  tflite: ^1.0.5
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  ios: true
  android: true
  image_path: "assets/logos/cu.jpg"  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/perros/labels.txt
    - assets/gatos/labels.txt
    - assets/osos/labels.txt
    - assets/logos/im.jpg
    - assets/perros/model_unquant.tflite
    - assets/gatos/model_unquant.tflite
    - assets/osos/model_unquant.tflite
    - assets/logos/cu.jpg
    - assets/fondos/fondo.jpg
    - assets/fondos/fonfop.jpg
    - assets/fondos/fondoo.png
    - assets/fondos/fondog.jpg
    - assets/perros/0.jpg
    - assets/perros/1.jpg
    - assets/perros/2.jpg
    - assets/perros/3.jpg
    - assets/perros/4.jpg
    - assets/perros/5.jpg
    - assets/perros/6.jpg
    - assets/perros/7.jpg
    - assets/perros/8.jpg
    - assets/gatos/0.jpg
    - assets/gatos/1.jpg
    - assets/gatos/2.jpg
    - assets/gatos/3.jpg
    - assets/gatos/4.jpg
    - assets/gatos/5.jpg
    - assets/gatos/6.jpg
    - assets/gatos/7.jpg
    - assets/osos/0.jpg
    - assets/osos/1.jpg
    - assets/osos/2.jpg
    - assets/osos/3.jpg
    - assets/imagenes/oso.png
    - assets/imagenes/gato.png
    - assets/imagenes/perro.png
    - assets/imagenes/dog.png
    - assets/imagenes/cat.png
    - assets/imagenes/im.jpg
    - assets/imagenes/bear.png


  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
